import type {
  AestheticScalar,
  ChatMessage,
  CreativeAsset,
  ImageVariant,
  SegmentAnnotation,
  StylePreset,
} from './types'

const byredoSourceTile = `${import.meta.env.BASE_URL}images/Image%20from%20iOS.jpg`
const byredoRemixOneTile = `${import.meta.env.BASE_URL}images/byredo-remix-1-seed-portrait.png`
const byredoMediaSize = { width: 853, height: 1844 }
const byredoRemixOneMediaSize = byredoMediaSize

export const assets: CreativeAsset[] = [
  { id: 'byredo-a', name: "BYREDO - Bal d'Afrique", channel: 'Instagram', version: 'v 1.0.2 [Current]' },
  { id: 'meta-b', name: 'Meta - Variant B', channel: 'Meta', version: 'v 1.0.1' },
  { id: 'reddit-c', name: 'Reddit - Variant C', channel: 'Reddit', version: 'v 0.9.8' },
]

const segmentSuggestions = {
  emotion: [
    {
      id: 'human-hook',
      label: 'Make faces the hook',
      impact: 8,
      promptHint: 'make the existing people or faces the emotional hook while preserving product and typography',
      scalarAdjustments: { presence: 12, staging: 7, gaze: 6, valence: 6 },
    },
    {
      id: 'warmer-moment',
      label: 'Warm the moment',
      impact: 5,
      promptHint: 'shift the human moment toward warmer emotional tone, softer expression, and a more inviting atmosphere',
      scalarAdjustments: { valence: 9, key: 5, chromatics: 4, hardness: -5 },
    },
    {
      id: 'candid-gesture',
      label: 'Find a candid gesture',
      impact: 4,
      promptHint: 'make the selected human area feel more candid through natural gesture and relaxed timing',
      scalarAdjustments: { staging: 10, arousal: -4, presence: 5 },
    },
  ],
  resonance: [
    {
      id: 'brand-hierarchy',
      label: 'Clarify brand hierarchy',
      impact: 5,
      promptHint: 'make the brand typography area more intentional, legible, and compositionally resolved without changing copy',
      scalarAdjustments: { complexity: -5, balance: 7, 'stopping-power': 7 },
    },
    {
      id: 'graphic-read',
      label: 'Simplify graphic read',
      impact: 4,
      promptHint: 'simplify the brand/copy area into a clearer graphic composition with stronger negative space',
      scalarAdjustments: { abstraction: 8, complexity: -9, balance: 6 },
    },
    {
      id: 'type-contrast',
      label: 'Improve type contrast',
      impact: 3,
      promptHint: 'improve contrast and separation around visible copy while preserving exact text and font logic',
      scalarAdjustments: { hardness: 6, key: -3, complexity: -5 },
    },
  ],
  product: [
    {
      id: 'product-hero',
      label: 'Make product the hero',
      impact: 5,
      promptHint: 'make the advertised product package more dominant, crisp, and shoppable while preserving exact SKU',
      scalarAdjustments: { groundedness: 6, 'stopping-power': 10, depth: 5, complexity: -4 },
    },
    {
      id: 'label-legibility',
      label: 'Sharpen label read',
      impact: 4,
      promptHint: 'increase product label legibility, glass clarity, and edge definition without inventing new packaging',
      scalarAdjustments: { hardness: 8, key: 4, materiality: 5, abstraction: -5 },
    },
    {
      id: 'premium-material',
      label: 'Elevate material cues',
      impact: 3,
      promptHint: 'make product materials feel more premium through controlled reflections and tactile surface cues',
      scalarAdjustments: { materiality: 10, hardness: 4, chromatics: 3 },
    },
  ],
  cta: [
    {
      id: 'cta-clarity',
      label: 'Increase CTA clarity',
      impact: 3,
      promptHint: 'make the CTA more legible and better separated while preserving exact wording and placement logic',
      scalarAdjustments: { complexity: -6, 'stopping-power': 7, balance: 4 },
    },
    {
      id: 'cta-breathing-room',
      label: 'Give CTA breathing room',
      impact: 2,
      promptHint: 'increase clean negative space around the CTA and reduce nearby visual interference',
      scalarAdjustments: { complexity: -8, balance: 5, abstraction: 3 },
    },
  ],
} satisfies Record<string, SegmentAnnotation['suggestions']>

export const originalSegments: SegmentAnnotation[] = [
  {
    id: 'emotion',
    label: 'Emotional engagement',
    x: 2,
    y: 25,
    width: 88,
    height: 43,
    delta: 7,
    suggestions: segmentSuggestions.emotion,
  },
  {
    id: 'resonance',
    label: 'Creative resonance',
    x: 25,
    y: 8,
    width: 52,
    height: 14,
    delta: 3,
    suggestions: segmentSuggestions.resonance,
  },
  {
    id: 'product',
    label: 'Product placement',
    x: 60,
    y: 73,
    width: 31,
    height: 16,
    delta: 0,
    suggestions: segmentSuggestions.product,
  },
  {
    id: 'cta',
    label: 'CTA',
    x: 39,
    y: 19,
    width: 24,
    height: 5,
    delta: 0,
    suggestions: segmentSuggestions.cta,
  },
]

export const updatedSegments: SegmentAnnotation[] = [
  {
    id: 'emotion',
    label: 'Emotional engagement',
    x: 5,
    y: 33,
    width: 78,
    height: 43,
    delta: 7,
    suggestions: segmentSuggestions.emotion,
  },
  {
    id: 'resonance',
    label: 'Creative resonance',
    x: 29,
    y: 9,
    width: 43,
    height: 18,
    delta: 3,
    suggestions: segmentSuggestions.resonance,
  },
  {
    id: 'product',
    label: 'Product placement',
    x: 58,
    y: 75,
    width: 33,
    height: 22,
    delta: 0,
    suggestions: segmentSuggestions.product,
  },
  {
    id: 'cta',
    label: 'CTA',
    x: 41,
    y: 22,
    width: 19,
    height: 4,
    delta: 0,
    suggestions: segmentSuggestions.cta,
  },
]

const originalVisualContext: ImageVariant['visualContext'] = {
  summary:
    "Vertical fragrance social ad for BYREDO Bal d'Afrique with two adults in cream styling seated on a sunlit coastal terrace, wide blue sky negative space, centered white brand typography near the top, and a perfume bottle anchored in the lower-right foreground.",
  locks: [
    'two seated adults in cream summer styling remain present',
    'same coastal terrace and blue-sky travel atmosphere',
    "exact BYREDO Bal d'Afrique perfume bottle remains in the lower-right foreground",
    'brand typography remains centered in the upper sky region',
    'CTA remains below the brand/subcopy stack',
    'sunlit stone ledge, sea horizon, and hillside remain recognizable',
    'preserve the tall vertical social-ad crop',
  ],
  textAnchors: [
    'centered BYREDO wordmark in the upper sky',
    "BAL D'AFRIQUE product line beneath the wordmark",
    'small italic campaign subcopy below the product line',
    'Shop Now CTA beneath the subcopy',
  ],
  product: {
    identity: "the exact BYREDO Bal d'Afrique eau de parfum bottle visible in the source image",
    packageType: 'clear rectangular fragrance bottle with pale yellow liquid, cream label, and glossy black rounded cap',
    visualSignature: [
      'clear glass bottle with rounded shoulders and transparent base',
      'large glossy black dome cap',
      "cream front label reading BYREDO and BAL D'AFRIQUE",
      'pale golden perfume liquid visible through the glass',
      'bottle placed on sunlit stone in the lower-right foreground',
    ],
    labelText: ['BYREDO', "BAL D'AFRIQUE", 'EAU DE PARFUM'],
    placement: 'lower-right foreground on the stone terrace surface, larger and sharper than the background figures',
    preservation: [
      'same SKU/product object as the source, not a different bottle, tube, box, pouch, candle, or product category',
      'same clear bottle silhouette, black cap, label color, label text, glass material, and scale',
      'composition may shift slightly, but the bottle must remain the recognizable source package',
    ],
  },
  typography: {
    family: 'BYREDO-style high-contrast serif wordmark with clean supporting sans and italic subcopy',
    fallback: 'use the font family identified from the source image pixels if the vision read detects a closer brand font',
    weight: 'wordmark uses refined light serif capitals; product line and CTA use light sans; subcopy uses delicate italic',
    style: 'centered white luxury fragrance typography integrated into the blue sky',
    casing: 'preserve source casing exactly, including BYREDO, BAL D’AFRIQUE, italic sentence subcopy, and Shop Now CTA',
    tracking: 'wide luxury letter spacing for the wordmark and product line',
    lineHeight: 'airy centered vertical stack matching the source',
    textRendering: [
      'match the source glyph geometry, x-height, curves, terminals, and numeral style',
      'preserve white text treatment and centered CTA alignment',
      'do not substitute generic bold sans, rounded fonts, or unrelated display lettering',
    ],
  },
  sourceDna: [
    "premium vertical social ad for BYREDO Bal d'Afrique",
    'sunlit Mediterranean/coastal terrace lifestyle photography with aspirational travel atmosphere',
    'two adults in cream linen-like summer clothing seated on a stone ledge and looking out toward the sea',
    'large blue-sky negative space in the upper half for centered brand typography',
    'sea horizon and green hillside in the mid/background',
    'sunlit stone surface and warm natural daylight',
    'clear BYREDO perfume bottle with black cap and cream label in the lower-right foreground',
    'luxury fragrance campaign composition with product sharpness and lifestyle depth',
    'tall portrait crop suitable for mobile/social placement',
  ],
  copywriting: [
    'BYREDO',
    "BAL D’AFRIQUE",
    'A celebration of culture, art and memory.',
    'Shop Now',
  ],
  avoid: [
    'extra people beyond the two source figures',
    'new product category',
    'new brand mark or invented bottle label',
    'full layout replacement',
    'cropping into a square',
    'moving the product away from the lower-right foreground',
  ],
}

const remixVisualContext: ImageVariant['visualContext'] = {
  ...originalVisualContext,
  summary:
    "Portrait BYREDO Bal d'Afrique remix with the same coastal terrace, two cream-styled figures, centered luxury typography, and product bottle, shifted into warmer golden-hour light with richer stone/glass texture and a more candid editorial read.",
  typography: {
    ...originalVisualContext.typography,
    family: 'BYREDO-style high-contrast serif wordmark with clean supporting sans and italic subcopy',
    style: 'centered white BYREDO wordmark, product line, italic subcopy, and Shop Now CTA matching the source ad system',
  },
  textAnchors: [
    'BYREDO wordmark in the upper sky',
    "BAL D'AFRIQUE line below it",
    'italic campaign subcopy',
    'Shop Now CTA',
  ],
  copywriting: [
    'BYREDO',
    "BAL D’AFRIQUE",
    'A celebration of culture, art and memory.',
    'Shop Now',
  ],
  sourceDna: [
    "source-preserving BYREDO Bal d'Afrique remix",
    'warmer golden-hour coastal terrace lifestyle photography',
    'two adults in cream linen-like summer clothing seated on the stone ledge and looking toward the sea',
    'centered white luxury typography preserved in the sky region',
    'clear BYREDO perfume bottle with glossy black cap and cream label enlarged in the lower-right foreground',
    'higher tactile read in stone, glass, linen, and warm sunlight',
    'portrait crop suitable for premium mobile/social placement',
  ],
}

const remixOneScalarRecipe: AestheticScalar[] = [
  {
    id: 'staging',
    label: 'Staging',
    lowLabel: 'Constructed',
    highLabel: 'Candid',
    value: 84,
    marker: '> Candid',
  },
  {
    id: 'abstraction',
    label: 'Abstraction',
    lowLabel: 'Literal',
    highLabel: 'Abstract',
    value: 34,
    marker: 'Literal',
  },
  {
    id: 'novelty',
    label: 'Novelty',
    lowLabel: 'Cliché',
    highLabel: 'Surreal',
    value: 76,
    marker: 'Surreal',
  },
  {
    id: 'materiality',
    label: 'Materiality',
    lowLabel: 'Digital',
    highLabel: 'Tactile',
    value: 66,
    marker: 'Tactile',
  },
  {
    id: 'hardness',
    label: 'Hardness',
    lowLabel: 'Soft',
    highLabel: 'Hard',
    value: 72,
    marker: 'Hard/Specular',
  },
  {
    id: 'key',
    label: 'Key',
    lowLabel: 'Low',
    highLabel: 'Bright',
    value: 86,
    marker: 'Warm/Bright',
  },
  {
    id: 'chromatics',
    label: 'Chromatics',
    lowLabel: 'Muted',
    highLabel: 'Vivid',
    value: 44,
    marker: 'Warm Natural',
  },
  {
    id: 'complexity',
    label: 'Complexity',
    lowLabel: 'Minimal',
    highLabel: 'Dense',
    value: 52,
    marker: 'Layered',
  },
  {
    id: 'balance',
    label: 'Balance',
    lowLabel: 'Static',
    highLabel: 'Tension',
    value: 62,
    marker: 'Dynamic/Tension',
  },
  {
    id: 'depth',
    label: 'Depth',
    lowLabel: 'Planar',
    highLabel: 'Deep',
    value: 42,
    marker: 'Room Context',
  },
  {
    id: 'groundedness',
    label: 'Groundedness',
    lowLabel: 'Abstract',
    highLabel: 'In Context',
    value: 92,
    marker: 'In Context',
  },
  {
    id: 'presence',
    label: 'Human Presence',
    lowLabel: 'None',
    highLabel: 'Present',
    value: 72,
    marker: 'Present',
  },
  {
    id: 'gaze',
    label: 'Gaze',
    lowLabel: 'Averted',
    highLabel: 'Direct',
    value: 58,
    marker: 'Averted',
  },
  {
    id: 'valence',
    label: 'Emotional Valence',
    lowLabel: 'Negative',
    highLabel: 'Positive',
    value: 88,
    marker: 'Positive',
  },
  {
    id: 'arousal',
    label: 'Arousal',
    lowLabel: 'Calm',
    highLabel: 'High',
    value: 42,
    marker: 'Lifted',
  },
  {
    id: 'stopping-power',
    label: 'Stopping Power',
    lowLabel: 'Low',
    highLabel: 'High',
    value: 68,
    marker: 'High',
  },
]

export const initialVariants: ImageVariant[] = [
  {
    id: 'original',
    title: 'Original Image',
    kind: 'original',
    image: byredoSourceTile,
    mediaSize: byredoMediaSize,
    score: 74,
    visualContext: originalVisualContext,
    segments: originalSegments,
  },
  {
    id: 'updated',
    title: 'Remix 1',
    kind: 'updated',
    image: byredoRemixOneTile,
    mediaSize: byredoRemixOneMediaSize,
    score: 83,
    delta: 9,
    visualContext: remixVisualContext,
    scalarRecipe: remixOneScalarRecipe,
    segments: updatedSegments,
  },
]

export const initialScalars: AestheticScalar[] = [
  {
    id: 'staging',
    label: 'Staging',
    lowLabel: 'Constructed',
    highLabel: 'Candid',
    value: 64,
    marker: 'Lifestyle staged',
  },
  {
    id: 'abstraction',
    label: 'Abstraction',
    lowLabel: 'Literal',
    highLabel: 'Abstract',
    value: 18,
    marker: 'Literal',
  },
  {
    id: 'novelty',
    label: 'Novelty',
    lowLabel: 'Cliché',
    highLabel: 'Surreal',
    value: 34,
    marker: 'Familiar',
  },
  {
    id: 'materiality',
    label: 'Materiality',
    lowLabel: 'Digital',
    highLabel: 'Tactile',
    value: 70,
    marker: 'Tactile',
  },
  {
    id: 'hardness',
    label: 'Hardness',
    lowLabel: 'Soft',
    highLabel: 'Hard',
    value: 72,
    marker: 'Hard/Specular',
  },
  {
    id: 'key',
    label: 'Key',
    lowLabel: 'Low',
    highLabel: 'Bright',
    value: 86,
    marker: 'Bright',
  },
  {
    id: 'chromatics',
    label: 'Chromatics',
    lowLabel: 'Muted',
    highLabel: 'Vivid',
    value: 58,
    marker: 'Natural',
  },
  {
    id: 'complexity',
    label: 'Complexity',
    lowLabel: 'Minimal',
    highLabel: 'Dense',
    value: 48,
    marker: 'Balanced',
  },
  {
    id: 'balance',
    label: 'Balance',
    lowLabel: 'Static',
    highLabel: 'Tension',
    value: 55,
    marker: 'Dynamic/Tension',
  },
  {
    id: 'depth',
    label: 'Depth',
    lowLabel: 'Planar',
    highLabel: 'Deep',
    value: 72,
    marker: 'Deep',
  },
  {
    id: 'groundedness',
    label: 'Groundedness',
    lowLabel: 'Abstract',
    highLabel: 'In Context',
    value: 95,
    marker: 'In Context',
  },
  {
    id: 'presence',
    label: 'Human Presence',
    lowLabel: 'None',
    highLabel: 'Present',
    value: 82,
    marker: 'Present',
  },
  {
    id: 'gaze',
    label: 'Gaze',
    lowLabel: 'Averted',
    highLabel: 'Direct',
    value: 24,
    marker: 'Averted',
  },
  {
    id: 'valence',
    label: 'Emotional Valence',
    lowLabel: 'Negative',
    highLabel: 'Positive',
    value: 88,
    marker: 'Positive',
  },
  {
    id: 'arousal',
    label: 'Arousal',
    lowLabel: 'Calm',
    highLabel: 'High',
    value: 32,
    marker: 'Calm',
  },
  {
    id: 'stopping-power',
    label: 'Stopping Power',
    lowLabel: 'Low',
    highLabel: 'High',
    value: 52,
    marker: 'Moderate',
  },
]

export const stylePresets: StylePreset[] = [
  {
    id: 'meta-campaign-dec',
    title: 'Meta - Campaign 12-Dec-202...',
    detail: 'Created 13 Dec 2025',
    scalarSettings: [
      { id: 'staging', value: 66, marker: 'Candid' },
      { id: 'abstraction', value: 28, marker: 'Literal' },
      { id: 'novelty', value: 64, marker: 'Balanced' },
      { id: 'materiality', value: 58, marker: 'Tactile' },
      { id: 'hardness', value: 72, marker: 'Hard/Specular' },
      { id: 'key', value: 82, marker: 'Warm/Bright' },
      { id: 'chromatics', value: 38, marker: 'Natural' },
      { id: 'complexity', value: 44, marker: 'Minimalist' },
      { id: 'balance', value: 54, marker: 'Dynamic/Tension' },
      { id: 'depth', value: 35, marker: 'Planar/Flat' },
      { id: 'groundedness', value: 88, marker: 'In Context' },
      { id: 'presence', value: 68, marker: 'Present' },
      { id: 'gaze', value: 74, marker: 'Direct' },
      { id: 'valence', value: 86, marker: 'Positive' },
      { id: 'arousal', value: 42, marker: 'Calm' },
      { id: 'stopping-power', value: 46, marker: 'Moderate' },
    ],
    context: {
      image: 'Face-forward beauty creative with warmer skin tone, visible product, and direct CTA.',
      audience: 'Meta prospecting, women 24-34, beauty and lifestyle interest clusters.',
      brand: 'Soft confidence tone, premium but approachable, no clinical language.',
      chat: ['Asked for more human warmth.', 'Kept the product visible without making it feel like a hard sell.'],
    },
  },
  {
    id: 'reddit-campaign-original',
    title: 'Original pre-set for Reddit ca...',
    detail: 'Created 27 Nov 2025',
    scalarSettings: [
      { id: 'staging', value: 42, marker: 'Constructed' },
      { id: 'abstraction', value: 18, marker: 'Literal' },
      { id: 'novelty', value: 36, marker: 'Familiar' },
      { id: 'materiality', value: 74, marker: 'Tactile' },
      { id: 'hardness', value: 48, marker: 'Soft/Natural' },
      { id: 'key', value: 56, marker: 'Mid' },
      { id: 'chromatics', value: 24, marker: 'Muted' },
      { id: 'complexity', value: 32, marker: 'Minimalist' },
      { id: 'balance', value: 38, marker: 'Stable' },
      { id: 'depth', value: 46, marker: 'Room Context' },
      { id: 'groundedness', value: 94, marker: 'In Context' },
      { id: 'presence', value: 52, marker: 'Present' },
      { id: 'gaze', value: 34, marker: 'Averted' },
      { id: 'valence', value: 68, marker: 'Positive' },
      { id: 'arousal', value: 22, marker: 'Calm' },
      { id: 'stopping-power', value: 30, marker: 'Quiet' },
    ],
    context: {
      image: 'Lower-polish lifestyle read with more literal product context and less editorial finish.',
      audience: 'Reddit skincare and beauty discussion audiences, value-led consideration stage.',
      brand: 'Practical, candid, peer-to-peer language with minimal performance-marketing gloss.',
      chat: ['User asked to reduce abstraction.', 'Assistant kept the styling grounded and conversational.'],
    },
  },
  {
    id: 'tiktok-creator-prospecting',
    title: 'TikTok - Creator prospecting',
    detail: 'Created 22 Nov 2025',
    scalarSettings: [
      { id: 'staging', value: 84, marker: 'Candid' },
      { id: 'abstraction', value: 34, marker: 'Literal' },
      { id: 'novelty', value: 82, marker: 'Surreal' },
      { id: 'materiality', value: 46, marker: 'Digital/Invisible' },
      { id: 'hardness', value: 62, marker: 'Crisp' },
      { id: 'key', value: 88, marker: 'Bright' },
      { id: 'chromatics', value: 54, marker: 'Warm Natural' },
      { id: 'complexity', value: 58, marker: 'Layered' },
      { id: 'balance', value: 63, marker: 'Dynamic/Tension' },
      { id: 'depth', value: 40, marker: 'Planar/Flat' },
      { id: 'groundedness', value: 78, marker: 'In Context' },
      { id: 'presence', value: 82, marker: 'Present' },
      { id: 'gaze', value: 80, marker: 'Direct' },
      { id: 'valence', value: 92, marker: 'Positive' },
      { id: 'arousal', value: 60, marker: 'Lifted' },
      { id: 'stopping-power', value: 76, marker: 'High' },
    ],
    context: {
      image: 'Creator-style crop with stronger expression, faster read, and higher scroll-stop pressure.',
      audience: 'TikTok broad prospecting, beauty creators, social shoppers, first-touch discovery.',
      brand: 'Confident, playful, social-native voice while preserving a premium visual baseline.',
      chat: ['Asked for a more trend-capable variant.', 'Assistant emphasized face visibility and CTA clarity.'],
    },
  },
  {
    id: 'shopify-retargeting-lift',
    title: 'Shopify - Retargeting lift',
    detail: 'Created 18 Nov 2025',
    scalarSettings: [
      { id: 'staging', value: 70, marker: 'Candid' },
      { id: 'abstraction', value: 20, marker: 'Literal' },
      { id: 'novelty', value: 48, marker: 'Balanced' },
      { id: 'materiality', value: 68, marker: 'Tactile' },
      { id: 'hardness', value: 76, marker: 'Hard/Specular' },
      { id: 'key', value: 78, marker: 'Bright' },
      { id: 'chromatics', value: 34, marker: 'Natural' },
      { id: 'complexity', value: 30, marker: 'Minimalist' },
      { id: 'balance', value: 44, marker: 'Stable' },
      { id: 'depth', value: 28, marker: 'Planar/Flat' },
      { id: 'groundedness', value: 92, marker: 'In Context' },
      { id: 'presence', value: 70, marker: 'Present' },
      { id: 'gaze', value: 66, marker: 'Direct' },
      { id: 'valence', value: 84, marker: 'Positive' },
      { id: 'arousal', value: 36, marker: 'Calm' },
      { id: 'stopping-power', value: 58, marker: 'Moderate' },
    ],
    context: {
      image: 'Shoppable retargeting variant with sharper CTA hierarchy and clear product crop.',
      audience: 'Returning site visitors and cart viewers with high purchase intent.',
      brand: 'Direct response language, clean premium finish, keep claims tight and credible.',
      chat: ['Asked for product placement clarity.', 'Assistant preserved the face while making the CTA easier to parse.'],
    },
  },
]

export const segments = originalSegments

export const initialMessages: ChatMessage[] = [
  {
    id: 'assistant-1',
    role: 'assistant',
    activity: 'Worked for 35s >',
    content:
      "Think of ways this can really trend on social media. Try showing people’s face in the image.",
  },
]
