import originalTile from './assets/creative/image-1.jpg'
import updatedTile from './assets/creative/image-2.jpg'
import type {
  AestheticScalar,
  ChatMessage,
  CreativeAsset,
  ImageVariant,
  SegmentAnnotation,
  StylePreset,
} from './types'

export const assets: CreativeAsset[] = [
  { id: 'tiktok-a', name: 'TikTok - Variant A', channel: 'TikTok', version: 'v 1.0.2 [Current]' },
  { id: 'meta-b', name: 'Meta - Variant B', channel: 'Meta', version: 'v 1.0.1' },
  { id: 'reddit-c', name: 'Reddit - Variant C', channel: 'Reddit', version: 'v 0.9.8' },
]

const segmentSuggestions = {
  emotion: [
    { id: 'face', label: 'Show more expression', impact: 9 },
    { id: 'tone', label: 'Warmer tone', impact: 4 },
    { id: 'lighting', label: 'Softer lighting', impact: 3 },
  ],
  resonance: [
    { id: 'copy', label: 'Make copy more intimate', impact: 5 },
    { id: 'contrast', label: 'Increase contrast', impact: 3 },
    { id: 'saturation', label: 'Reduce saturation', impact: 2 },
  ],
  product: [
    { id: 'brighten', label: 'Increase brightness', impact: 2 },
    { id: 'contrast', label: 'Increase contrast', impact: 2 },
    { id: 'warmth', label: 'Warmth', impact: 1 },
    { id: 'sat', label: 'Reduce saturation', impact: 1 },
  ],
  cta: [
    { id: 'clarity', label: 'Increase CTA clarity', impact: 2 },
    { id: 'button', label: 'Sharpen button contrast', impact: 2 },
  ],
} satisfies Record<string, SegmentAnnotation['suggestions']>

export const originalSegments: SegmentAnnotation[] = [
  {
    id: 'emotion',
    label: 'Emotional engagement',
    x: 39,
    y: 7,
    width: 25,
    height: 23,
    delta: 7,
    suggestions: segmentSuggestions.emotion,
  },
  {
    id: 'resonance',
    label: 'Creative resonance',
    x: 4,
    y: 32,
    width: 80,
    height: 30,
    delta: 3,
    suggestions: segmentSuggestions.resonance,
  },
  {
    id: 'product',
    label: 'Product placement',
    x: 40,
    y: 63,
    width: 28,
    height: 20,
    delta: 0,
    suggestions: segmentSuggestions.product,
  },
  {
    id: 'cta',
    label: 'CTA',
    x: 3,
    y: 86,
    width: 47,
    height: 11,
    delta: 0,
    suggestions: segmentSuggestions.cta,
  },
]

export const updatedSegments: SegmentAnnotation[] = [
  {
    id: 'emotion',
    label: 'Emotional engagement',
    x: 41,
    y: 6,
    width: 22,
    height: 23,
    delta: 7,
    suggestions: segmentSuggestions.emotion,
  },
  {
    id: 'resonance',
    label: 'Creative resonance',
    x: 5,
    y: 35,
    width: 82,
    height: 31,
    delta: 3,
    suggestions: segmentSuggestions.resonance,
  },
  {
    id: 'product',
    label: 'Product placement',
    x: 39,
    y: 62,
    width: 28,
    height: 19,
    delta: 0,
    suggestions: segmentSuggestions.product,
  },
  {
    id: 'cta',
    label: 'CTA',
    x: 3,
    y: 84,
    width: 48,
    height: 12,
    delta: 0,
    suggestions: segmentSuggestions.cta,
  },
]

const originalVisualContext: ImageVariant['visualContext'] = {
  summary:
    'Square social ad creative with one seated person in a warm tan interior crop, dark marble surface at the left edge, large white headline copy across the middle, dark rectangular product package held near the lower center, blue denim visible in the lower frame, and a compact CTA in the lower-left corner.',
  locks: [
    'one human subject only',
    'same seated/cropped body arrangement',
    'dark product remains held near the lower center',
    'headline region stays across the center of the frame',
    'CTA remains in the lower-left region',
    'warm wall/shadow backdrop remains recognizable',
    'blue denim and seated lower-body crop remain recognizable',
  ],
  textAnchors: [
    'large central headline',
    'small italic subcopy under the headline',
    'lower-left CTA button',
  ],
  typography: {
    family: 'Inter',
    fallback: 'use the font family identified from the source image pixels if the vision read detects a closer brand font',
    weight: 'headline uses regular-to-medium sans weight; CTA uses bold uppercase sans',
    style: 'large white social ad headline with compact italic subcopy and bold CTA label',
    casing: 'preserve source casing exactly, including sentence case headline and uppercase CTA',
    tracking: 'tight default tracking, no decorative letter spacing',
    lineHeight: 'compact stacked headline line-height matching the source',
    textRendering: [
      'match the source glyph geometry, x-height, curves, terminals, and numeral style',
      'preserve white text treatment and CTA button text alignment',
      'do not substitute display, serif, script, condensed, or rounded fonts',
    ],
  },
  sourceDna: [
    'warm tan editorial beauty-ad lighting',
    'square social crop with large native text overlay',
    'minimal sans typography integrated into the photography',
    'lower-left CTA and centered headline hierarchy',
  ],
  copywriting: [
    '“You smell so good! I noticed the minute you walked in”',
    'My barista this morning',
    'SHOP BRALESS NOW',
  ],
  avoid: [
    'extra people',
    'new product category',
    'new brand mark or invented bottle label',
    'full layout replacement',
    'moving the product out of the hand/lower-center region',
  ],
}

const remixVisualContext: ImageVariant['visualContext'] = {
  ...originalVisualContext,
  summary:
    'Square social ad remix with one seated person in the same warm tan interior layout, face visible in the upper-right crop, cream top and blue denim lower-frame crop, dark marble surface at the left edge, dark rectangular product package held near the lower center, large white headline copy over the torso, italic subcopy below, and lower-left CTA.',
  typography: {
    ...originalVisualContext.typography,
    family: 'Inter',
    style: 'large white stacked headline, small italic subcopy, and bold uppercase CTA matching the source ad system',
  },
  textAnchors: [
    'Radiate Confidence / Feel Beautiful headline structure',
    'small italic morning/barista subcopy',
    'lower-left CTA button',
  ],
  copywriting: [
    'Radiate Confidence. Feel Beautiful Inside & Out',
    'My barista this morning yet.',
    'SHOP BRALESS NOW',
  ],
}

export const initialVariants: ImageVariant[] = [
  {
    id: 'original',
    title: 'Original Image',
    kind: 'original',
    image: originalTile,
    score: 74,
    visualContext: originalVisualContext,
    segments: originalSegments,
  },
  {
    id: 'updated',
    title: 'Remix 1',
    kind: 'updated',
    image: updatedTile,
    score: 83,
    delta: 7,
    visualContext: remixVisualContext,
    segments: updatedSegments,
  },
]

export const initialScalars: AestheticScalar[] = [
  {
    id: 'staging',
    label: 'Staging',
    lowLabel: 'Constructed',
    highLabel: 'Candid',
    value: 78,
    marker: '> Candid',
  },
  {
    id: 'abstraction',
    label: 'Abstraction',
    lowLabel: 'Literal',
    highLabel: 'Abstract',
    value: 23,
    marker: '> Literal',
  },
  {
    id: 'novelty',
    label: 'Novelty',
    lowLabel: 'Cliché',
    highLabel: 'Surreal',
    value: 58,
    marker: 'Balanced',
  },
  {
    id: 'materiality',
    label: 'Materiality',
    lowLabel: 'Digital',
    highLabel: 'Tactile',
    value: 50,
    marker: 'Digital/Invisible',
  },
  {
    id: 'hardness',
    label: 'Hardness',
    lowLabel: 'Soft',
    highLabel: 'Hard',
    value: 80,
    marker: 'Hard/Specular',
  },
  {
    id: 'key',
    label: 'Key',
    lowLabel: 'Low',
    highLabel: 'Bright',
    value: 100,
    marker: 'Low/Dark',
  },
  {
    id: 'chromatics',
    label: 'Chromatics',
    lowLabel: 'Muted',
    highLabel: 'Vivid',
    value: 30,
    marker: 'Natural',
  },
  {
    id: 'complexity',
    label: 'Complexity',
    lowLabel: 'Minimal',
    highLabel: 'Dense',
    value: 40,
    marker: 'Minimalist',
  },
  {
    id: 'balance',
    label: 'Balance',
    lowLabel: 'Static',
    highLabel: 'Tension',
    value: 50,
    marker: 'Dynamic/Tension',
  },
  {
    id: 'depth',
    label: 'Depth',
    lowLabel: 'Planar',
    highLabel: 'Deep',
    value: 20,
    marker: 'Planar/Flat',
  },
  {
    id: 'groundedness',
    label: 'Groundedness',
    lowLabel: 'Abstract',
    highLabel: 'In Context',
    value: 100,
    marker: 'In Context',
  },
  {
    id: 'presence',
    label: 'Human Presence',
    lowLabel: 'None',
    highLabel: 'Present',
    value: 0,
    marker: 'None',
  },
  {
    id: 'gaze',
    label: 'Gaze',
    lowLabel: 'Averted',
    highLabel: 'Direct',
    value: 50,
    marker: 'Averted',
  },
  {
    id: 'valence',
    label: 'Emotional Valence',
    lowLabel: 'Negative',
    highLabel: 'Positive',
    value: 90,
    marker: 'Positive',
  },
  {
    id: 'arousal',
    label: 'Arousal',
    lowLabel: 'Calm',
    highLabel: 'High',
    value: 30,
    marker: 'Calm',
  },
  {
    id: 'stopping-power',
    label: 'Stopping Power',
    lowLabel: 'Low',
    highLabel: 'High',
    value: 10,
    marker: 'Quiet',
  },
]

export const stylePresets: StylePreset[] = [
  {
    id: 'meta-campaign-dec',
    title: 'Meta - Campaign 12-Dec-202...',
    detail: 'Created 13 Dec 2025',
    scalarSettings: [
      { id: 'staging', value: 66, marker: 'Candid' },
      { id: 'abstraction', value: 28, marker: 'Literal' },
      { id: 'novelty', value: 64, marker: 'Balanced' },
      { id: 'materiality', value: 58, marker: 'Tactile' },
      { id: 'hardness', value: 72, marker: 'Hard/Specular' },
      { id: 'key', value: 82, marker: 'Warm/Bright' },
      { id: 'chromatics', value: 38, marker: 'Natural' },
      { id: 'complexity', value: 44, marker: 'Minimalist' },
      { id: 'balance', value: 54, marker: 'Dynamic/Tension' },
      { id: 'depth', value: 35, marker: 'Planar/Flat' },
      { id: 'groundedness', value: 88, marker: 'In Context' },
      { id: 'presence', value: 68, marker: 'Present' },
      { id: 'gaze', value: 74, marker: 'Direct' },
      { id: 'valence', value: 86, marker: 'Positive' },
      { id: 'arousal', value: 42, marker: 'Calm' },
      { id: 'stopping-power', value: 46, marker: 'Moderate' },
    ],
    context: {
      image: 'Face-forward beauty creative with warmer skin tone, visible product, and direct CTA.',
      audience: 'Meta prospecting, women 24-34, beauty and lifestyle interest clusters.',
      brand: 'Soft confidence tone, premium but approachable, no clinical language.',
      chat: ['Asked for more human warmth.', 'Kept the product visible without making it feel like a hard sell.'],
    },
  },
  {
    id: 'reddit-campaign-original',
    title: 'Original pre-set for Reddit ca...',
    detail: 'Created 27 Nov 2025',
    scalarSettings: [
      { id: 'staging', value: 42, marker: 'Constructed' },
      { id: 'abstraction', value: 18, marker: 'Literal' },
      { id: 'novelty', value: 36, marker: 'Familiar' },
      { id: 'materiality', value: 74, marker: 'Tactile' },
      { id: 'hardness', value: 48, marker: 'Soft/Natural' },
      { id: 'key', value: 56, marker: 'Mid' },
      { id: 'chromatics', value: 24, marker: 'Muted' },
      { id: 'complexity', value: 32, marker: 'Minimalist' },
      { id: 'balance', value: 38, marker: 'Stable' },
      { id: 'depth', value: 46, marker: 'Room Context' },
      { id: 'groundedness', value: 94, marker: 'In Context' },
      { id: 'presence', value: 52, marker: 'Present' },
      { id: 'gaze', value: 34, marker: 'Averted' },
      { id: 'valence', value: 68, marker: 'Positive' },
      { id: 'arousal', value: 22, marker: 'Calm' },
      { id: 'stopping-power', value: 30, marker: 'Quiet' },
    ],
    context: {
      image: 'Lower-polish lifestyle read with more literal product context and less editorial finish.',
      audience: 'Reddit skincare and beauty discussion audiences, value-led consideration stage.',
      brand: 'Practical, candid, peer-to-peer language with minimal performance-marketing gloss.',
      chat: ['User asked to reduce abstraction.', 'Assistant kept the styling grounded and conversational.'],
    },
  },
  {
    id: 'tiktok-creator-prospecting',
    title: 'TikTok - Creator prospecting',
    detail: 'Created 22 Nov 2025',
    scalarSettings: [
      { id: 'staging', value: 84, marker: 'Candid' },
      { id: 'abstraction', value: 34, marker: 'Literal' },
      { id: 'novelty', value: 82, marker: 'Surreal' },
      { id: 'materiality', value: 46, marker: 'Digital/Invisible' },
      { id: 'hardness', value: 62, marker: 'Crisp' },
      { id: 'key', value: 88, marker: 'Bright' },
      { id: 'chromatics', value: 54, marker: 'Warm Natural' },
      { id: 'complexity', value: 58, marker: 'Layered' },
      { id: 'balance', value: 63, marker: 'Dynamic/Tension' },
      { id: 'depth', value: 40, marker: 'Planar/Flat' },
      { id: 'groundedness', value: 78, marker: 'In Context' },
      { id: 'presence', value: 82, marker: 'Present' },
      { id: 'gaze', value: 80, marker: 'Direct' },
      { id: 'valence', value: 92, marker: 'Positive' },
      { id: 'arousal', value: 60, marker: 'Lifted' },
      { id: 'stopping-power', value: 76, marker: 'High' },
    ],
    context: {
      image: 'Creator-style crop with stronger expression, faster read, and higher scroll-stop pressure.',
      audience: 'TikTok broad prospecting, beauty creators, social shoppers, first-touch discovery.',
      brand: 'Confident, playful, social-native voice while preserving a premium visual baseline.',
      chat: ['Asked for a more trend-capable variant.', 'Assistant emphasized face visibility and CTA clarity.'],
    },
  },
  {
    id: 'shopify-retargeting-lift',
    title: 'Shopify - Retargeting lift',
    detail: 'Created 18 Nov 2025',
    scalarSettings: [
      { id: 'staging', value: 70, marker: 'Candid' },
      { id: 'abstraction', value: 20, marker: 'Literal' },
      { id: 'novelty', value: 48, marker: 'Balanced' },
      { id: 'materiality', value: 68, marker: 'Tactile' },
      { id: 'hardness', value: 76, marker: 'Hard/Specular' },
      { id: 'key', value: 78, marker: 'Bright' },
      { id: 'chromatics', value: 34, marker: 'Natural' },
      { id: 'complexity', value: 30, marker: 'Minimalist' },
      { id: 'balance', value: 44, marker: 'Stable' },
      { id: 'depth', value: 28, marker: 'Planar/Flat' },
      { id: 'groundedness', value: 92, marker: 'In Context' },
      { id: 'presence', value: 70, marker: 'Present' },
      { id: 'gaze', value: 66, marker: 'Direct' },
      { id: 'valence', value: 84, marker: 'Positive' },
      { id: 'arousal', value: 36, marker: 'Calm' },
      { id: 'stopping-power', value: 58, marker: 'Moderate' },
    ],
    context: {
      image: 'Shoppable retargeting variant with sharper CTA hierarchy and clear product crop.',
      audience: 'Returning site visitors and cart viewers with high purchase intent.',
      brand: 'Direct response language, clean premium finish, keep claims tight and credible.',
      chat: ['Asked for product placement clarity.', 'Assistant preserved the face while making the CTA easier to parse.'],
    },
  },
]

export const segments = originalSegments

export const initialMessages: ChatMessage[] = [
  {
    id: 'assistant-1',
    role: 'assistant',
    activity: 'Worked for 35s >',
    content:
      "Think of ways this can really trend on social media. Try showing people’s face in the image.",
  },
]
